"""Aggregate the four experiment results into a single comparison table.

Inputs (relative to rag_test root):
    experiments/exp-003-hipporag2-gpt/results/hipporag2_gpt_metrics.json
    experiments/exp-004-raptor-gpt/results/raptor_gpt_metrics.json
    experiments/exp-005-comorag-narrativeqa/results/comorag_metrics.json
    experiments/exp-006-arag-narrativeqa/results/eval_summary.json

Output: prints a Markdown table to stdout AND writes
    reports/RAG_COMPARISON_NARRATIVEQA_table.md
"""
import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
RAG_TEST = _HERE.parent

SYSTEMS = [
    {
        "label": "HippoRAG 2 (gpt-4.1-mini, 140-tok)",
        "file": "experiments/exp-003-hipporag2-gpt/results/hipporag2_gpt_metrics.json",
        "schema": "flat",  # top-level F1/EM/ROUGE-L/...
    },
    {
        "label": "RAPTOR (gpt-4.1-mini, 140-tok)",
        "file": "experiments/exp-004-raptor-gpt/results/raptor_gpt_metrics.json",
        "schema": "flat",
    },
    {
        "label": "ComoRAG (gpt-4.1-mini, 140-tok)",
        "file": "experiments/exp-005-comorag-narrativeqa/results/comorag_metrics.json",
        "schema": "flat",
    },
    {
        "label": "A-RAG raw (gpt-4.1-mini, 140-tok)",
        "file": "experiments/exp-006-arag-narrativeqa/results/eval_summary.json",
        "schema": "nested.raw",
    },
    {
        "label": "A-RAG cleaned (gpt-4.1-mini, 140-tok)",
        "file": "experiments/exp-006-arag-narrativeqa/results/eval_summary.json",
        "schema": "nested.cleaned",
    },
]

METRICS = ["F1", "EM", "ROUGE-L", "BLEU-1", "BLEU-4", "METEOR"]


def extract(d, schema):
    if schema == "flat":
        return d
    if schema.startswith("nested."):
        key = schema.split(".", 1)[1]
        return d.get(key, {})
    raise ValueError(f"unknown schema: {schema}")


def fmt(v):
    if v is None:
        return "—"
    return f"{float(v):.2f}"


def main():
    rows = []
    for sys_meta in SYSTEMS:
        fp = RAG_TEST / sys_meta["file"]
        if not fp.exists():
            print(f"[warn] missing: {fp} — leaving row blank", file=sys.stderr)
            metrics = {}
        else:
            d = json.load(open(fp))
            metrics = extract(d, sys_meta["schema"])
        rows.append((sys_meta["label"], metrics))

    # Markdown table
    lines = []
    header = "| System | " + " | ".join(METRICS) + " |"
    sep = "|" + "---|" * (len(METRICS) + 1)
    lines.append(header)
    lines.append(sep)
    for label, metrics in rows:
        cells = [label] + [fmt(metrics.get(m)) for m in METRICS]
        lines.append("| " + " | ".join(cells) + " |")

    table_md = "\n".join(lines)
    print("\n## NarrativeQA dev_10_doc — RAG comparison (gpt-4.1-mini + SBERT, n=293)\n")
    print(table_md)

    out = RAG_TEST / "reports" / "RAG_COMPARISON_NARRATIVEQA_table.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as f:
        f.write("# NarrativeQA dev_10_doc — auto-generated comparison\n\n")
        f.write("Last regenerated by `scripts/build_comparison.py`. Source files:\n")
        for s in SYSTEMS:
            f.write(f"- `{s['file']}` ({s['schema']})\n")
        f.write("\n")
        f.write(table_md)
        f.write("\n")
    print(f"\nWritten: {out}")


if __name__ == "__main__":
    main()
